function [] = Cashier(~, User, Chip_Val, fig1, ~,~)
% Cashier initiates a uifigure (fig2) prompting Doge Blackjack players to
% purchase chips.
%   Input arguements
%       "New_Game_Btn"
%   Output arguements
%       None

Cashier_fig = uiimage(fig1, 'Position', [150 0 750 735] );                 
       Cashier_fig.ImageSource = 'backgrounds\Cashier.jpg';

Balance_Label = uilabel(fig1, 'Position', [970 445 65 22],              ...
                            'HorizontalAlignment', 'right',             ...
                            'FontSize', 16,                             ...
                            'FontColor', [.15 .7 0], 'Text', 'Cash   $');

Balance = uieditfield(fig1, 'numeric', 'Limits', [0 Inf],               ...
                           'Editable', 'off',                           ...
                           'ValueDisplayFormat', '%9.0f',               ...
                           'FontSize', 16,                              ...
                           'FontColor', [.15 .7 0],                     ...
                           'HorizontalAlignment', 'center',             ...
                           'BackgroundColor', [0.1 0.1 0.1],            ...
                           'Position', [1040 445 70 22], 'Value', 1000);

Chip_lim = Balance.Value / Chip_Val;

Buy_Chips_Spnr = uispinner(fig1, 'Position', [970 330 75 30], 'FontSize',...
                            16,'Limits', [0 Chip_lim], 'ValueChangedFcn',...
                           @(Buy_Chips_Spnr,event) Balance_Changing());

    function Balance_Changing()
        Balance.Value = 1000 - Buy_Chips_Spnr.Value * Chip_Val;
        User.Balance = Balance.Value;
    end

Buy_Max = uibutton(fig1, 'push',                                        ...
                         'BackgroundColor', [0.85 0.85 0.85],           ...
                         'Position', [1060 325 60 40],                  ...
                         'FontSize', 18, 'FontWeight', 'bold',          ...
                         'VerticalAlignment', 'Center',                 ...
                     'FontColor', 'White', 'BackgroundColor', '#73d12e',...
                    'Text', 'max', 'ButtonPushedfcn', @(Buy_Max, event) ...
                      Max_Chip(Buy_Max, Buy_Chips_Spnr));

    function Max_Chip(~, Buy_Chips_Spnr)
        Buy_Chips_Spnr.Value = 1000 / Chip_Val;
        Balance.Value = 0; 
    end

Play_Btn = uibutton(fig1, 'push',                                       ...
                          'BackgroundColor', [1 0.5 0.15],              ...
                          'Position', [1000 215 100 40],                ...
                          'FontSize', 18, 'FontWeight', 'bold',         ...
                          'FontColor', 'Black',                         ...
                          'VerticalAlignment', 'Center',                ...
                          'Text', 'Let''s Play!',                       ...
                          'ButtonPushedFcn', @(Play_Btn, event)         ...
                          update_Val(Play_Btn, Buy_Chips_Spnr));

    function [] = update_Val(Play_Btn, Buy_Chips_Spnr)
        if Buy_Chips_Spnr.Value > 0
            User.Chips = Buy_Chips_Spnr.Value;
            clf(fig1);
            Table(Play_Btn, User, Chip_Val, fig1);
        end
    end  
end