function [] = Cashier(user,chip_val)
% Cashier initiates a uifigure (fig2) prompting Doge Blackjack players to
% purchase chips.
%   Input arguements
%       user
%       chip_val
%   Output arguements
%       None
fig2 = uifigure('Name', 'Doge Blackjack - Cashier',                     ...
                    'Position', [215 56 1080 720],                      ...
                    'Color', 'black', 'Pointer','hand', 'Visible', 'off');

Cashier_fig = uiimage(fig2, 'Position', [175 45 750 701] );                 
       Cashier_fig.ImageSource = 'backgrounds\Cashier.jpg';

Balance_Label = uilabel(fig2, 'Position', [65 625 65 22],               ...
                             'HorizontalAlignment', 'right',            ...
                             'FontSize', 16,                            ...
                             'FontColor', [.15 .7 0], 'Text', 'Cash   $');

Balance = uieditfield(fig2, 'numeric', 'Limits', [0 Inf],               ...
                           'Editable', 'off',                           ...
                           'ValueDisplayFormat', '%9.0f',               ...
                           'FontSize', 16,                              ...
                           'FontColor', [.15 .7 0],                     ...
                           'HorizontalAlignment', 'center',             ...
                           'BackgroundColor', [0.1 0.1 0.1],            ...
                           'Position', [135 625 70 22], 'Value', user.money);

Buy_Chips_Spnr_Lbl = uilabel(fig2, 'BackgroundColor', '#e6e6e6',        ...
                                 'Position', [430 250 315 22],          ...
                                 'FontSize', 14, 'FontWeight', 'Bold',  ...
                                 'HorizontalAlignment', 'Center');
       Buy_Chips_Spnr_Lbl.Text = 'Welcome! How many chips would you like?';


Buy_Chips_Spnr = uispinner(fig2, 'Position', [510 218 65 22],           ...
          'Limits', [0 (user.money/chip_val)], 'ValueChangedFcn', @(Buy_Chips_Spnr,event)...
            Balance_Changing(Balance,Buy_Chips_Spnr));

    function Balance_Changing(Balance,Buy_Chips_Spnr)
        Balance.Value = user.money - Buy_Chips_Spnr.Value * chip_val;
        user.chips = Buy_Chips_Spnr.Value;
        user.money = Balance.Value;
    end

Buy_Max = uibutton(fig2, 'push',                                        ...
                          'BackgroundColor', [0.85 0.85 0.85],          ...
                          'Position', [595 217 50 25],                  ...
                          'FontSize', 14, 'FontWeight', 'bold',         ...
                          'VerticalAlignment', 'Center',                ...
                     'FontColor', 'White', 'BackgroundColor', '#73d12e',...
                    'Text', 'max', 'ButtonPushedfcn', @(Buy_Max, event) ...
                      Max_Chip(Buy_Max, Buy_Chips_Spnr));

    function Max_Chip(Buy_Max, Buy_Chips_Spnr)
        total_amount = user.money/chip_val;
        max_chips_val = floor(total_amount);
        Buy_Chips_Spnr.Value = max_chips_val;
        Balance.Value = user.money - max_chips_val*total_amount; 
        user.money = user.money - max_chips_val*total_amount;
        user.chips = max_chips_val;
    end

Play_Btn = uibutton(fig2, 'push',                                       ...
                          'BackgroundColor', [0.85 0.85 0.85],          ...
                          'Position', [495 180 100 25],                 ...
                          'FontSize', 14, 'FontWeight', 'bold',         ...
                          'FontColor', 'Black',                         ...
                          'VerticalAlignment', 'Center',                ...
                          'Text', 'Let''s Play!',                       ...
                          'ButtonPushedFcn', @(Play_Btn, event)         ...
                          update_Val(Play_Btn, Buy_Chips_Spnr));

    function [] = update_Val(Play_Btn, Buy_Chips_Spnr)
        if user.chips > 0
            close(fig2);
            Table(user, chip_val);
        else
            selection = uiconfirm(fig2,'You have no chips! Hit ok to buy chips or hit cancel to end the game!',...
            'No Chips!');
        switch selection
            case 'OK'
                Cashier(user,chip_val);
            case 'Cancel'
                exit;
        end
    end  

fig2.Visible = 'on';

end