function Table(Play_Btn, Chips, Chip_Val, Start_Bal)
% Doge_Blackjack initiates a uifigure (fig3) and the Blackjack game 
% environment. Doge_Blackjack incorporates features such as
% multiple betting options, balance tracking, restart, and cashout/exit.
%   Input arguements
%       Play_Btn
%       Chips
%       Chip_Val
%       Start_Bal
%   Output arguements
%       None

Chip_Bal = Chips * Chip_Val;

fig3 = uifigure('Name', 'Doge Blackjack',                               ...
                    'Position', [128 56 1280 720],                      ...
                    'Color', 'black', 'Pointer','hand', 'Visible', 'off');

    % Generates Blackjack table and dealer graphics.
fig_Start = uiimage(fig3, 'BackgroundColor', 'Black',                   ...
                         'Position', [0 0 1280 720]);
       fig_Start.ImageSource = 'backgrounds\Main.jpeg';

    % Balance appears in top left corner
        % Balance label
Balance_Label = uilabel(fig3, 'Position', [120 650 125 22],             ...
                             'HorizontalAlignment', 'right',            ...
                             'FontSize', 16, ...
                        'FontColor', [.15 .7 0], 'Text', 'Chips Balance  $');

        % Balance value
Balance = uieditfield(fig3, 'numeric', 'Limits', [0 Inf],               ...
                           'Editable', 'off',                           ...
                           'ValueDisplayFormat', '%9.0f',               ...
                           'FontSize', 16,                              ...
                           'FontColor', [.15 .7 0],                     ...
                           'HorizontalAlignment', 'center',             ...
                           'BackgroundColor', [0.1 0.1 0.1],            ...
                           'Position', [250 650 86 22], 'Value', Chip_Bal);
 

    % Chip label
Chip_Label = uilabel(fig3, 'HorizontalAlignment', 'center',             ...
                          'FontSize', 16,                               ...
                          'FontColor', [.8 .8 .8],                      ...
                          'Position', [185 615 63 22],                  ...
                          'Text', 'Chips');

    % Chip quantity owned
Chip_Qty = uieditfield(fig3, 'numeric', 'Limits', [0 Inf],         ...
                                 'ValueDisplayFormat', '%5.0f',         ...
                                 'Editable', 'off',                     ...
                                 'Position', [250 615 86 22],           ...
                                 'HorizontalAlignment', 'center',       ...
                                 'BackgroundColor', [0.1 0.1 0.1],      ...
                                 'FontSize', 16,                        ...
                                 'FontColor', [.8 .8 .8]);
                                Chip_Qty.Value = Chips;


    % Button allowing user to buy more chips during gameplay if desired
Restart_Btn = uibutton(fig3, 'push', ...
                                'BackgroundColor', [0.15 0.15 0.15],    ...
                                'FontSize', 14, 'FontWeight', 'bold',   ...
                                'FontColor', [.8 .8 .8],                ...
                                'Position', [380 613 85 26],           ...
                                'Text', 'Restart',                      ...
                         'ButtonPushedFcn', @(Restart_Btn, event)       ...
                                 Restart());

    function [] = Restart()
        uiconfirm(fig3, 'Leaving will reset your balance. Do you wish to continue?', ...
                        'Restart', 'Icon', 'warning', 'CloseFcn', @Restart_Game);
    end

    function Restart_Game(src, event)
        if event.SelectedOption == "OK"
            close(fig3);
            Cashier;
        end
    end

Cashout_Btn = uibutton(fig3, 'push', 'FontSize', 14,                    ...
                                     'FontWeight', 'bold',              ...
                                    'BackgroundColor', [0.15 0.15 0.15],...
                                     'FontColor', [.15 .7 0],           ...
                                     'Position', [350 649 150 26],      ...
                                     'Text', 'CASHOUT AND EXIT',        ...
                                'ButtonPushedFcn', @(Cashout_Btn, event)...
                                 Exit());
    function [] = Exit()
        uiconfirm(fig3, 'Do you wish to exit the game?',                ...
                    'Exit', 'Icon', 'warning', 'CloseFcn', @Exit_Game);
    end

    function Exit_Game(src, event)
        if event.SelectedOption == "OK"
            Cashout(Cashout_Btn, Chip_Bal, Start_Bal);
        end
    end


%       Betting
Current_Bet_Label = uilabel(fig3, 'HorizontalAlignment', 'center',      ...
                              'VerticalAlignment', 'center', 'Fontsize',...
                              18, 'FontColor', [1 0.4 0.15], 'Position',...
                              [150 525 98 23], 'Text', 'Current Bet');                 

%       Current Bet value displayed
Current_Bet = uieditfield(fig3, 'numeric', 'Limits', [0 Inf],          ...
                            'Editable', 'off', 'ValueDisplayFormat',    ...
                            '%9.0f', 'HorizontalAlignment', 'center',   ...
                            'FontSize', 18, 'FontColor', [1 0.4 0.15],  ...
                           'BackgroundColor', [0.1 0.1 0.1], 'Position',...
                            [265 525 108 24], 'Value', 0);


    %Bet 1 Chip
Btn_25 = uibutton(fig3, 'push', 'BackgroundColor', [0.05 0.25 0.0],     ...
                           'Position', [100 450 64 56], 'Text', '',     ...
                          'ButtonPushedFcn', @(Btn_25, event)           ...
                           Bet25(Btn_25,Chip_Qty, Current_Bet));   
       Btn_25.Icon = 'buttons\single25.png';

    function Bet25(Btn_25, Chip_Qty, Current_Bet)
            if Chip_Qty.Value >= 1
                Current_Bet.Value = Current_Bet.Value + 1;
                Chip_Qty.Value = Chip_Qty.Value - 1;
            end

    end

    %Bet 2 chips
Btn_50 = uibutton(fig3, 'push', 'BackgroundColor', [0.05 0.25 0.0],     ...
                           'Position', [185 450 64 56], 'Text', '',     ...
                           'ButtonPushedFcn', @(Btn_50, event)          ...
                           Bet50(Btn_50, Chip_Qty, Current_Bet));
       Btn_50.Icon = 'buttons\single50.png';

    function Bet50(Btn_50, Chip_Qty, Current_Bet)
            if Chip_Qty.Value >= 2
                Current_Bet.Value = Current_Bet.Value + 2;
                Chip_Qty.Value = Chip_Qty.Value - 2;

            else
                Current_Bet.Value = Current_Bet.Value + Chip_Qty.Value;
                Chip_Qty.Value = 0;
                
            end
    end

    %Bet 4 chips
Btn_100 = uibutton(fig3, 'push', 'BackgroundColor', [0.05 0.25 0.0],    ...
                            'Position', [270 450 64 56], 'Text', '',    ...
                            'ButtonPushedFcn', @(Btn_100, event)        ...
                           Bet100(Btn_100, Chip_Qty, Current_Bet));  
       Btn_100.Icon = 'buttons\single100.png';

    function Bet100(Btn_100, Chip_Qty, Current_Bet)
            if Chip_Qty.Value >= 4
                Current_Bet.Value = Current_Bet.Value + 4;
                Chip_Qty.Value = Chip_Qty.Value - 4;
                
            else
                Current_Bet.Value = Current_Bet.Value + Chip_Qty.Value;
                Chip_Qty.Value = 0;

            end
    end

    %Bet 20 chips
Btn_500 = uibutton(fig3, 'push', 'BackgroundColor', [0.05 0.25 0.0],    ...
                            'Position', [355 450 64 56], 'Text', '',    ...
                            'ButtonPushedFcn', @(Btn_500, event)        ...
                  Bet500(Btn_500, Chip_Qty, Current_Bet));  
       Btn_500.Icon = 'buttons\single500.png';

    function Bet500(Btn_500, Chip_Qty, Current_Bet)
            if Chip_Qty.Value >= 20
                Current_Bet.Value = Current_Bet.Value + 20;
                Chip_Qty.Value = Chip_Qty.Value - 20;

            else
                Current_Bet.Value = Current_Bet.Value + Chip_Qty.Value;
                Chip_Qty.Value = 0;

            end
    end

    %Bet 40 chips
Btn_1000 = uibutton(fig3, 'push', 'BackgroundColor', [0.05 0.25 0.0],   ...
                             'Position', [440 450 64 56], 'Text', '',   ...
                             'ButtonPushedFcn', @(Btn_1000, event)      ...
                  Bet1000(Btn_1000, Chip_Qty, Current_Bet)); 
       Btn_1000.Icon = 'buttons\single1000.png';

    function Bet1000(Btn_1000, Chip_Qty, Current_Bet)
            if Chip_Qty.Value >= 40
                Current_Bet.Value = Current_Bet.Value + 40;
                Chip_Qty.Value = Chip_Qty.Value - 40;

            else
                Current_Bet.Value = Current_Bet.Value + Chip_Qty.Value;
                Chip_Qty.Value = 0;

            end
    end

Clr_Bet_Btn = uibutton(fig3, 'push', 'FontSize', 14, 'FontWeight',      ...
                                 'bold', 'FontColor', [1 1 1],          ...
                                 'BackgroundColor', [0.15 0.15 0.15],   ...
                       'Position', [385 524 96 26], 'Text', 'CLEAR BET',...
                                'ButtonPushedfcn', @(Clr_Bet_Btn, event)...
                                Clr_Bet(Clr_Bet_Btn, Current_Bet, Chip_Qty));

    function Clr_Bet(Clr_Bet_Btn, Current_Bet, Chip_Qty)
        Chip_Qty.Value = Chip_Qty.Value + Current_Bet.Value;
        Current_Bet.Value = 0;
    end

Deal_Btn = uibutton(fig3, 'push', 'BackgroundColor', [0.9 0.9 0.9],     ...
                          'FontSize', 16, 'FontWeight', 'bold',         ...
                       'Position', [250 375 96 30], 'Text', 'DEAL EM!', ...
                          'ButtonPushedFcn', @(Deal_Btn, event)         ...
                          Deal_Lim(Deal_Btn, Current_Bet));

    function [] = Deal_Lim(Deal_Btn, Current_Bet)
        if Current_Bet.Value > 0
            Deal_Cards(Deal_Btn, Balance, Current_Bet_Label,            ...
                    Current_Bet, Btn_25, Btn_50, Btn_100, Btn_500,      ...
                    Btn_1000, Clr_Bet_Btn, Restart_Btn, Cashout_Btn, fig3);
        end
    end

fig3.Visible = 'on';

end